### ISSUE TITLE
invalid byte sequence in UTF-8

### ISSUE THREAD

**Issue by emn178** [ruby-av/av#14]
Hi,

I use paperclip and got errors when upload specific video files,

```
     ArgumentError:
       invalid byte sequence in UTF-8
     # /Users/emn178/.rvm/gems/ruby-2.2.2/gems/av-0.9.0/lib/av/commands/base.rb:98:in `split'
     # /Users/emn178/.rvm/gems/ruby-2.2.2/gems/av-0.9.0/lib/av/commands/base.rb:98:in `identify'
     # /Users/emn178/.rvm/gems/ruby-2.2.2/gems/av-0.9.0/lib/av/cli.rb:19:in `method_missing'
     # /Users/emn178/.rvm/gems/ruby-2.2.2/gems/paperclip-av-transcoder-0.6.4/lib/paperclip/paperclip_processors/transcoder.rb:15:in `initialize'
...
```

The command it ran is:

```
[AV] Running command: ffmpeg -i "/var/folders/9f/sv32jzv53451kysr4v8l6jf40000gn/T/d35f70211135de265bc7c66df4dd360520150905-36894-k4jbwc.mp4" 2>&1
```

I ran command in terminal manually and got something liket this:

```
...
  Duration: 01:25:18.69, start: 0.000000, bitrate: 236 kb/s
    Stream #0:0(eng): Audio: aac (LC) (mp4a / 0x6134706D), 32000 Hz, mono, fltp, 31 kb/s (default)
    Metadata:
      creation_time   : 2015-04-20 22:42:29
      handler_name    : Apple Án­µ´CÅé³B²z¾¹
...
```

There are something encoding issues and cause uploading failed.
Please help to fixed this problem.

Thank and best regards.

**Comment by emn178** [comment]
Hi,

I found this problem has been solved in master branch. 
So I will use master before you release new version.

``` Ruby
gem 'av', :git => 'https://github.com/ruby-av/av.git'
```
